apiVersion: apps/v1
kind: Deployment
metadata:
  name: epsilla-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epsilla-pod
  template:
    metadata:
      labels:
        app: epsilla-pod
    spec:
      containers:
      - name: epsilla-container
        image: epsilla/vectordb:latest
        ports:
        - containerPort: 8888
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/Mexico_City
---
apiVersion: v1
kind: Service
metadata:
  name: epsilla-svc
spec:
  selector:
    app: epsilla-pod
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  type: ClusterIP